# fly.toml app configuration file generated for agolf on 2024-01-21T15:09:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "agolf"
primary_region = "den"
kill_signal = "SIGTERM"

[build]

[mounts]
  source = "agolf_data"
  destination = "/data"

[env]
  DATABASE_PATH = "/data/agolf_data/agolf_prod.db"
  PHX_HOST = "agolf.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
